collections:
  - name: "yazilim" # Used in routes, e.g., /admin/collections/blog
    label: "Yazılım"
    description: "Yazılım - kelime ekle" # Used in the UI
    folder: "src/content/docs/yazilim" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Kelime (Armut, Elma)", name: "title", widget: "string" }
      - { label: "Açıklama (Orijinal K. -> Çeviri)", name: "description", widget: "string" }
      - { label: "Paylaşım tarihi", name: "date", widget: "datetime" }
      - { label: "Arama, Açıklama, Örnek", name: "body", widget: "markdown" }
  - name: "donanim" # Used in routes, e.g., /admin/collections/donanim
    label: "Donanım"
    description: "Donanım - kelime ekle" # Used in the UI
    folder: "src/content/docs/donanim" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Kelime (Armut, Elma)", name: "title", widget: "string" }
      - { label: "Açıklama (Orijinal K. -> Çeviri)", name: "description", widget: "string" }
      - { label: "Paylaşım tarihi", name: "date", widget: "datetime" }
      - { label: "Arama, Açıklama, Örnek", name: "body", widget: "markdown" }
  - name: "bilim" # Used in routes, e.g., /admin/collections/bilim
    label: "Bilim"
    description: "Bilim - kelime ekle" # Used in the UI
    folder: "src/content/docs/bilim" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Kelime (Armut, Elma)", name: "title", widget: "string" }
      - { label: "Açıklama (Orijinal K. -> Çeviri)", name: "description", widget: "string" }
      - { label: "Paylaşım tarihi", name: "date", widget: "datetime" }
      - { label: "Arama, Açıklama, Örnek", name: "body", widget: "markdown" }
  - name: "doldurucular" # Used in routes, e.g., /admin/collections/doldurucular
    label: "Doldurucular"
    description: "Doldurucular - kelime ekle" # Used in the UI
    folder: "src/content/docs/doldurucular" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Kelime (Armut, Elma)", name: "title", widget: "string" }
      - { label: "Açıklama (Orijinal K. -> Çeviri)", name: "description", widget: "string" }
      - { label: "Paylaşım tarihi", name: "date", widget: "datetime" }
      - { label: "Arama, Açıklama, Örnek", name: "body", widget: "markdown" }
  - name: "felsefe" # Used in routes, e.g., /admin/collections/felsefe
    label: "Felsefe"
    description: "Felsefe - kelime ekle" # Used in the UI
    folder: "src/content/docs/felsefe" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Kelime (Armut, Elma)", name: "title", widget: "string" }
      - { label: "Açıklama (Orijinal K. -> Çeviri)", name: "description", widget: "string" }
      - { label: "Paylaşım tarihi", name: "date", widget: "datetime" }
      - { label: "Arama, Açıklama, Örnek", name: "body", widget: "markdown" }
  - name: "gunluk-hayat" # Used in routes, e.g., /admin/collections/gunluk-hayat
    label: "Günlük Hayat"
    description: "Günlük Hayat - kelime ekle" # Used in the UI
    folder: "src/content/docs/gunluk-hayat" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Kelime (Armut, Elma)", name: "title", widget: "string" }
      - { label: "Açıklama (Orijinal K. -> Çeviri)", name: "description", widget: "string" }
      - { label: "Paylaşım tarihi", name: "date", widget: "datetime" }
      - { label: "Arama, Açıklama, Örnek", name: "body", widget: "markdown" }
  - name: "hayvanlar" # Used in routes, e.g., /admin/collections/hayvanlar
    label: "Hayvanlar"
    description: "Hayvanlar - kelime ekle" # Used in the UI
    folder: "src/content/docs/hayvanlar" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Kelime (Armut, Elma)", name: "title", widget: "string" }
      - { label: "Açıklama (Orijinal K. -> Çeviri)", name: "description", widget: "string" }
      - { label: "Paylaşım tarihi", name: "date", widget: "datetime" }
      - { label: "Arama, Açıklama, Örnek", name: "body", widget: "markdown" }
  - name: "tarih" # Used in routes, e.g., /admin/collections/tarih
    label: "Tarih"
    description: "Tarih - kelime ekle" # Used in the UI
    folder: "src/content/docs/tarih" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Kelime (Armut, Elma)", name: "title", widget: "string" }
      - { label: "Açıklama (Orijinal K. -> Çeviri)", name: "description", widget: "string" }
      - { label: "Paylaşım tarihi", name: "date", widget: "datetime" }
      - { label: "Arama, Açıklama, Örnek", name: "body", widget: "markdown" }
  - name: "teoloji" # Used in routes, e.g., /admin/collections/teoloji
    label: "Teoloji"
    description: "Teoloji - kelime ekle" # Used in the UI
    folder: "src/content/docs/teoloji" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Kelime (Armut, Elma)", name: "title", widget: "string" }
      - { label: "Açıklama (Orijinal K. -> Çeviri)", name: "description", widget: "string" }
      - { label: "Paylaşım tarihi", name: "date", widget: "datetime" }
      - { label: "Arama, Açıklama, Örnek", name: "body", widget: "markdown" }
  - name: "tip" # Used in routes, e.g., /admin/collections/tip
    label: "Tip"
    description: "Tip - kelime ekle" # Used in the UI
    folder: "src/content/docs/tip"
    create: true 
    fields:
      - { label: "Kelime (Armut, Elma)", name: "title", widget: "string" }
      - { label: "Açıklama (Orijinal K. -> Çeviri)", name: "description", widget: "string" }
      - { label: "Paylaşım tarihi", name: "date", widget: "datetime" }
      - { label: "Arama, Açıklama, Örnek", name: "body", widget: "markdown" }

backend:
  name: github
  repo: onrirr/tonga
  open_authoring: true
  auth_scope: repo

publish_mode: editorial_workflow
media_folder: "static/images/uploads" 
public_folder: "/images/uploads"